name: rainitas-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - streamlit>=1.34
  # general
  - pandas>=2.2
  - plotly>=5.22
  - python-dotenv>=1.0
  - tabulate>=0.9
  # fiako-stations
  - geopy>=2.4
  - pytables>=3.9
  # hidrokit-rainfall
  - statsmodels>=0.14
  # fiako-anfrek
  - scipy>=1.13
  # LLM
  - openai>=1.26
  # test
  - pytest>=8.2
  - pip
  - pip:
    - hidrokit>=0.5
